### ISSUE TITLE
Known Initial Release Issues/To-Do List

### ISSUE THREAD

**Issue by Shoukaku-Kai** [Shoukaku-Kai/Gergasi-Hypermarket-V2#1]
**Customer Form:** 
- [x] "Include" button is still empty
- [x] "Pay" button is still empty
- [x] Array has yet to be constructed and Total Cost calculation has yer to be implemented
- [x] Frequently Purchased Items when click doesn't add up to the total cost in array
- [x] "Remove Previous" does not delete the last array value

**Staff Login Form:**
- [x] Login  button does nothing

**Staff Form:**
- [x] It's very hollow

**Misc Issues:**
- [x] Database has yet to be set up properly
